apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-12T06:50:35Z"
  name: order-canary
  resourceVersion: "289386"
  selfLink: /api/v1/namespaces/keptnorders-production/services/order
  uid: b2d6c82c-1cab-11ea-b21c-42010aa40100
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: order
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
