apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-11T18:12:19Z"
  name: frontend-canary
  resourceVersion: "118960"
  selfLink: /api/v1/namespaces/keptnorders-production/services/frontend
  uid: c53e5fdb-1c41-11ea-b21c-42010aa40100
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
