apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-11T11:23:10Z"
  name: customer-canary
  resourceVersion: "26274"
  selfLink: /api/v1/namespaces/keptnorders-production/services/customer
  uid: 9ca8c6d9-1c08-11ea-b21c-42010aa40100
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: customer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
